# Start from an x86 image of Alpine Linux configured for Python projects
FROM frolvlad/alpine-python3

# Update the package cache and bash
RUN apk update
RUN apk add --update bash

# Set /src to be the working directory and copy in the project files
WORKDIR /src
ADD server.py /src
ADD static_server.py /src
ADD ping_server.py /src
ADD uploads /src/uploads
ADD requirements.txt /src

# Install the project's dependencies
RUN pip3 install -r requirements.txt

# Expose the port used by the server
EXPOSE 8765 8766 8767

# Run the server unless overridden
CMD python3.5 -u ./server.py
